const CadiaCommand = require('../../lib/structures/commands/CadiaCommand');
const { color, emojis } = require('../../config');
const {
	ActionRowBuilder,
	ButtonBuilder,
	ButtonStyle,
	ContainerBuilder,
	MediaGalleryBuilder,
	MediaGalleryItemBuilder,
	MessageFlags,
	SeparatorBuilder,
	SeparatorSpacingSize,
	TextDisplayBuilder
} = require('discord.js');

const fetch = (...args) => import('node-fetch').then(({ default: fetch }) => fetch(...args));

class UserCommand extends CadiaCommand {
	constructor(context, options) {
		super(context, {
			...options,
			description: 'Generate a husbando Image'
		});
	}

	registerApplicationCommands(registry) {
		registry.registerChatInputCommand((builder) => builder.setName('husbando').setDescription(this.description));
	}

	async chatInputRun(interaction) {
		try {
			await interaction.deferReply({ flags: MessageFlags.IsComponentsV2 });
			const res = await fetch('https://nekos.best/api/v2/husbando');
			const img = (await res.json()).results?.[0]?.url;
			if (!img) throw new Error('No husbando image returned');

			const container = new ContainerBuilder()
				.setAccentColor(Number.parseInt(color.default.replace('#', ''), 16))
				.addTextDisplayComponents(new TextDisplayBuilder().setContent(`${emojis.custom.heart2} **Husbando Generated**`))
				.addSeparatorComponents(new SeparatorBuilder().setDivider(true).setSpacing(SeparatorSpacingSize.Small))
				.addMediaGalleryComponents(
					new MediaGalleryBuilder().addItems(new MediaGalleryItemBuilder().setURL(img).setDescription('Husbando image'))
				)
				.addSeparatorComponents(new SeparatorBuilder().setDivider(true).setSpacing(SeparatorSpacingSize.Small))
				.addTextDisplayComponents(
					new TextDisplayBuilder().setContent(`${emojis.custom.person} Generated by **${interaction.user.displayName}**`)
				)
				.addActionRowComponents(
					new ActionRowBuilder().addComponents(new ButtonBuilder().setLabel('Open Image').setStyle(ButtonStyle.Link).setURL(img))
				);

			await interaction.editReply({
				components: [container],
				flags: MessageFlags.IsComponentsV2
			});
		} catch (error) {
			console.error(error);
			await interaction.editReply({
				components: [
					new ContainerBuilder()
						.setAccentColor(Number.parseInt(color.fail.replace('#', ''), 16))
						.addTextDisplayComponents(
							new TextDisplayBuilder().setContent(`${emojis.custom.fail} I could not generate an image right now.`)
						)
				],
				flags: MessageFlags.IsComponentsV2
			});
		}
	}
}

module.exports = {
	UserCommand
};
