const CadiaCommand = require('../../lib/structures/commands/CadiaCommand');
const { color, emojis } = require('../../config');
const {
	ActionRowBuilder,
	ButtonBuilder,
	ButtonStyle,
	ContainerBuilder,
	MediaGalleryBuilder,
	MediaGalleryItemBuilder,
	MessageFlags,
	SeparatorBuilder,
	SeparatorSpacingSize,
	TextDisplayBuilder
} = require('discord.js');

const fetch = (...args) => import('node-fetch').then(({ default: fetch }) => fetch(...args));

const endpointByCategory = {
	'marin-kitagawa': 'waifu',
	'mori-calliope': 'waifu',
	'raiden-shogun': 'waifu',
	waifu: 'waifu',
	maid: 'waifu',
	oppai: 'waifu',
	selfies: 'neko',
	uniform: 'waifu'
};

class UserCommand extends CadiaCommand {
	constructor(context, options) {
		super(context, {
			...options,
			description: 'Generate a waifu Image'
		});
	}

	registerApplicationCommands(registry) {
		registry.registerChatInputCommand((builder) =>
			builder
				.setName('waifu')
				.setDescription(this.description)
				.addStringOption((option) =>
					option
						.setName('category')
						.setDescription('Choose your category')
						.setRequired(true)
						.addChoices(
							{ name: 'Marin Kitagawa', value: 'marin-kitagawa' },
							{ name: 'Mori Calliope', value: 'mori-calliope' },
							{ name: 'Raiden Shogun', value: 'raiden-shogun' },
							{ name: 'Waifu', value: 'waifu' },
							{ name: 'Maid', value: 'maid' },
							{ name: 'Oppai', value: 'oppai' },
							{ name: 'Selfies', value: 'selfies' },
							{ name: 'Uniform', value: 'uniform' }
						)
				)
		);
	}

	async chatInputRun(interaction) {
		try {
			await interaction.deferReply({ flags: MessageFlags.IsComponentsV2 });

			const type = interaction.options.getString('category');
			const result = await fetchImage(type);
			const image = result.url;

			if (!image) throw new Error('No waifu image returned');

			await interaction.editReply({
				components: [buildImageContainer(interaction, 'Waifu Generated', type, result)],
				flags: MessageFlags.IsComponentsV2
			});
		} catch (error) {
			console.error(error);
			await interaction.editReply({
				components: [
					new ContainerBuilder()
						.setAccentColor(Number.parseInt(color.fail.replace('#', ''), 16))
						.addTextDisplayComponents(
							new TextDisplayBuilder().setContent(`${emojis.custom.fail} I could not generate an image right now.`)
						)
				],
				flags: MessageFlags.IsComponentsV2
			});
		}
	}
}

async function fetchImage(category) {
	const endpoint = endpointByCategory[category] ?? 'waifu';
	const response = await fetch(`https://nekos.best/api/v2/${endpoint}`, {
		headers: {
			accept: 'application/json',
			'user-agent': 'Cadia-Bot/1.3.0'
		}
	});
	const contentType = response.headers.get('content-type') ?? '';

	if (!response.ok || !contentType.includes('application/json')) {
		throw new Error(`Waifu API returned ${response.status} ${contentType || 'unknown content type'}`);
	}

	const body = await response.json();
	const result = body.results?.[0];

	if (!result?.url) throw new Error('Waifu API returned no image');
	return result;
}

function buildImageContainer(interaction, title, category, result) {
	const image = result.url;
	const artist = result.artist_name || 'Unknown artist';

	return new ContainerBuilder()
		.setAccentColor(Number.parseInt(color.default.replace('#', ''), 16))
		.addTextDisplayComponents(
			new TextDisplayBuilder().setContent(`${emojis.custom.heart2} **${title}**\n${emojis.custom.openfolder} Category: \`${category}\``)
		)
		.addSeparatorComponents(new SeparatorBuilder().setDivider(true).setSpacing(SeparatorSpacingSize.Small))
		.addMediaGalleryComponents(new MediaGalleryBuilder().addItems(new MediaGalleryItemBuilder().setURL(image).setDescription(title)))
		.addSeparatorComponents(new SeparatorBuilder().setDivider(true).setSpacing(SeparatorSpacingSize.Small))
		.addTextDisplayComponents(
			new TextDisplayBuilder().setContent(
				`${emojis.custom.person} Generated by **${interaction.user.displayName}**\n${emojis.custom.pencil} Artist: **${artist}**`
			)
		)
		.addActionRowComponents(
			new ActionRowBuilder().addComponents(
				...[
					new ButtonBuilder().setLabel('Open Image').setStyle(ButtonStyle.Link).setURL(image),
					buildOptionalLinkButton('Source', result.source_url),
					buildOptionalLinkButton('Artist', result.artist_href)
				].filter(Boolean)
			)
		);
}

function buildOptionalLinkButton(label, url) {
	if (!url?.startsWith('http')) return null;
	return new ButtonBuilder().setLabel(label).setStyle(ButtonStyle.Link).setURL(url);
}

module.exports = {
	UserCommand
};
